name: life
description: Personal diary application

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  intl: ^0.19.0
  isar: 
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  iconsax: ^0.0.8
  timezone: ^0.9.4
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  time_machine: ^0.9.17
  dynamic_color: ^1.7.0
  path_provider: ^2.1.4
  table_calendar: ^3.1.2
  flutter_timezone: ^3.0.1
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  isar_flutter_libs:
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  flutter_displaymode: ^0.6.0
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  isar_generator: 
    version: ^3.1.8
    hosted: https://pub.isar-community.dev/
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#181818"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter_native_splash:
  color: "#181818"
  android_12:
    color: "#181818"
  image: "assets/icons/icon.png"

flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/google_fonts/
